site_name: CAPJu Docs
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
extra_css:
  - stylesheets/styles.css
dev_addr: "0.0.0.0:8000"
nav:
  - Sobre: index.md
  - Planejamento: 
  - Produto:
    - Visão do Produto: produto/visao.md
    - Backlog do Produto: produto/backlog_do_produto.md
    - Protótipo: produto/prototipo.md
  - Comunicacao:
    - Documento de comunicacao: comunicacao/comunicacao.md
  - Reuniões:
    - Reuniões com o Cliente: 
      - Kick-off: relatorios/semana1/Kick-off.md
    - Reuniões da Equipe:
      - Reunião de interação: relatorios/semana1/Reuniao_de_interacao.md
  - Projeto:
    - Documento de arquitetura: projeto/arquitetura.md 
    - Documento de custos: projeto/custos.md
    - EAP: projeto/eap.md
    - GCS: projeto/gcs.md
    - Documento de riscos: projeto/riscos.md